//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityFarmer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActivityFarmer()
        {
            this.ActivityOrders = new HashSet<ActivityOrder>();
        }
    
        public int ActivityFarmerID { get; set; }
        public Nullable<int> ActivityPhotoID { get; set; }
        public int SupplierID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string ActivityName { get; set; }
        public string ActivityAddress { get; set; }
        public Nullable<int> MaxQuantity { get; set; }
        public Nullable<int> GroupQuantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public string ActivityContent { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string ATMBank { get; set; }
        public string ATMAccount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    
        public virtual ActivityCity ActivityCity { get; set; }
        public virtual ActivityPhoto ActivityPhoto { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityOrder> ActivityOrders { get; set; }
    }
}
