//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AllFarmsDBEntities : DbContext
    {
        public AllFarmsDBEntities()
            : base("name=AllFarmsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityCity> ActivityCities { get; set; }
        public virtual DbSet<ActivityFarmer> ActivityFarmers { get; set; }
        public virtual DbSet<ActivityOrder> ActivityOrders { get; set; }
        public virtual DbSet<ActivityPhoto> ActivityPhotoes { get; set; }
        public virtual DbSet<AddressInfo> AddressInfoes { get; set; }
        public virtual DbSet<Advertising> Advertisings { get; set; }
        public virtual DbSet<BlackListInfo> BlackListInfoes { get; set; }
        public virtual DbSet<Browse> Browses { get; set; }
        public virtual DbSet<ChatLog> ChatLogs { get; set; }
        public virtual DbSet<CustomerInfo> CustomerInfoes { get; set; }
        public virtual DbSet<CustomerLoginlog> CustomerLoginlogs { get; set; }
        public virtual DbSet<CustomerRefund> CustomerRefunds { get; set; }
        public virtual DbSet<CustomerReturn> CustomerReturns { get; set; }
        public virtual DbSet<CustomerSubscription> CustomerSubscriptions { get; set; }
        public virtual DbSet<DiscountPointsEvent> DiscountPointsEvents { get; set; }
        public virtual DbSet<DiscountPointsEventDetail> DiscountPointsEventDetails { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<PostalCodeInfo> PostalCodeInfoes { get; set; }
        public virtual DbSet<ProductGrowPlanDetail> ProductGrowPlanDetails { get; set; }
        public virtual DbSet<ProductGrowPlanMaster> ProductGrowPlanMasters { get; set; }
        public virtual DbSet<ProductImage> ProductImages { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<SaleEvent> SaleEvents { get; set; }
        public virtual DbSet<SaleEventCombo> SaleEventComboes { get; set; }
        public virtual DbSet<SaleEventQuota> SaleEventQuotas { get; set; }
        public virtual DbSet<SaleEventSingleProduct> SaleEventSingleProducts { get; set; }
        public virtual DbSet<ShoppingCart> ShoppingCarts { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<SuppliersBulletinBoard> SuppliersBulletinBoards { get; set; }
        public virtual DbSet<SuppliersFarm> SuppliersFarms { get; set; }
        public virtual DbSet<SuppliersStoryDetail> SuppliersStoryDetails { get; set; }
        public virtual DbSet<SuppliersStoryMaster> SuppliersStoryMasters { get; set; }
        public virtual DbSet<SuppliersVideo> SuppliersVideos { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<SystemToSuppliersInfo> SystemToSuppliersInfoes { get; set; }
    }
}
