//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerReturn
    {
        public int ReturnID { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<bool> ReturnOrder { get; set; }
        public string ReturnReason { get; set; }
        public Nullable<int> Quantity { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    }
}
