//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSubscription
    {
        public int SubscriptionID { get; set; }
        public int CustomerID { get; set; }
        public int SuppliersID { get; set; }
        public System.DateTime SubscriptionDate { get; set; }
        public Nullable<bool> AllowMail { get; set; }
    
        public virtual CustomerInfo CustomerInfo { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
