<?xml version="1.0" encoding="utf-8"?><Database Name="farmsDB" Class="DataLINQtoSQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=farmsDB;Integrated Security=True" SettingsObjectName="WpfFarmsSupplier.Properties.Settings" SettingsPropertyName="farmsDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Suppliers" Member="Suppliers">
    <Type Name="Suppliers">
      <Column Name="SupplierID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SupplierName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ContactName1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ContactName2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone1" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Phone2" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="LineID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastUpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastUpdateUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Suppliers_SuppliersVedio" Member="SuppliersVedio" ThisKey="SupplierID" OtherKey="SuppliersID" Type="SuppliersVedio" />
    </Type>
  </Table>
  <Table Name="dbo.SuppliersVedio" Member="SuppliersVedio">
    <Type Name="SuppliersVedio">
      <Column Name="SuppliersStoryID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SuppliersID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SuppliersStoryTitle" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdateUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Suppliers_SuppliersVedio" Member="Suppliers" ThisKey="SuppliersID" OtherKey="SupplierID" Type="Suppliers" IsForeignKey="true" />
    </Type>
  </Table>
</Database>