//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllFarmsData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityOrder
    {
        public Nullable<int> ActivityFarmerID { get; set; }
        public int ActivityOrderID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string ATMBank { get; set; }
        public string ATMAccount { get; set; }
        public Nullable<bool> GroupConfirm { get; set; }
        public Nullable<bool> PaymentConfirm { get; set; }
        public Nullable<bool> ReceivedConfirm { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    
        public virtual ActivityFarmer ActivityFarmer { get; set; }
    }
}
