//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFarmsActivity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductGrowPlanMaster
    {
        public int SupplierFarmID { get; set; }
        public int ProductGrowID { get; set; }
        public string ProductKind { get; set; }
        public Nullable<System.DateTime> Planting { get; set; }
        public Nullable<System.DateTime> PlanHarvestDate { get; set; }
        public Nullable<int> PlanHarvestQTY { get; set; }
        public Nullable<int> ActuallyarvestQTY { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedDateUserID { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<int> LastUpdateUserID { get; set; }
    
        public virtual ProductGrowPlanDetail ProductGrowPlanDetail { get; set; }
        public virtual SuppliersFarm SuppliersFarm { get; set; }
    }
}
